export enum IconSize {
  SMALL = "SMALL",
  MEDIUM = "NORMAL",
  LARGE = "LARGE",
  EXTRA_LARGE = "EXTRA_LARGE",
}

export enum IconType {
  CHECKMARK = "CHECKMARK",
  PROJECT = "PROJECT",
  DASHBOARD = "DASHBOARD",
  SETTINGS = "SETTINGS",
  TIME = "TIME",
  ARROWX = "ARROWX",
  ARROWY = "ARROWY",
  MENU_ARROW = "MENU_ARROW",
  NOTIFICATION = "NOTIFICATION",
  AVATAR = "AVATAR",
  SIDEBAR_LOGO = "SIDEBAR_LOGO",
  PENDING_FIX = "PENDING_FIX",
  FIXED = "FIXED",
  ACCEPTED_RISKS = "ACCEPTED_RISKS",
  CALENDAR = "CALENDAR",
}
